version: '3.8'

services:

  gateway_app:
    container_name: gateway
    image: gateway-img
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    networks:
      - alonetwork
    depends_on:
      - configserver_app
      - eurekaServer_app

  microservice_producto_app:
    container_name: microservice-producto
    image: microservice-producto-img
    build:
      context: ./microservice-producto
      dockerfile: Dockerfile
    ports:
      - 8092:8092
    restart: always
    networks:
      - alonetwork
    depends_on:
      - configserver_app
      - eurekaServer_app

  microservice_user_app:
    container_name: microservice-user
    image: microservice-user-img
    build:
      context: ./microservice-user
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    restart: always
    networks:
      - alonetwork
    depends_on:
      - configserver_app
      - eurekaServer_app

  microservice_ordenes_app:
    container_name: microservice-ordenes
    image: microservice-ordenes-img
    build:
      context: ./microservice-ordenes
      dockerfile: Dockerfile
    ports:
      - 8091:8091
    restart: always
    networks:
      - alonetwork
    depends_on:
      - configserver_app
      - eurekaServer_app

  eurekaServer_app:
    container_name: eurekaServer
    image: eurekaserver-img
    build:
      context: ./eurekaServer
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: always
    networks:
      - alonetwork
    depends_on:
      - configserver_app

  configserver_app:
    container_name: configServer
    image: configserver-img
    build:
      context: ./configServer
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    restart: always
    networks:
      - alonetwork

networks:
  alonetwork:
    driver: bridge


