version: '4.0'

networks:
  localNetwork:
    driver: bridge

services:
  microservice_ordenes_app:
    container_name: microservice-ordenes
    image: microservice-ordenes-img
    build:
      context: ./microservice-ordenes
      dockerfile: Dockerfile
    ports:
      - 8091:8091
    depends_on:
      - eurekaServer_app
    networks:
      - localNetwork

  eurekaServer_app:
    container_name: eurekaServer
    image: eurekaserver-img
    build:
      context: ./eurekaServer
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - configserver_app
    networks:
      - localNetwork

  configserver_app:
    container_name: configServer
    image: configserver-img
    build:
      context: ./configServer
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    networks:
      - localNetwork




