version: '3.8'

services:
  gateway:
    container_name: gateway
    image: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      CONFIG_URI: http://config-server:8888
      EUREKA_URI: http://eureka-server:8081/eureka/
    restart: always
    networks:
      - alonetwork
    depends_on:
      - config-server
      - eureka-server

  microservice-producto:
    container_name: microservice-producto
    image: microservice-producto
    build:
      context: ./microservice-producto
      dockerfile: Dockerfile
    ports:
      - 8092:8092
    environment:
      CONFIG_URI: http://config-server:8888
      EUREKA_URI: http://eureka-server:8081/eureka/
    restart: on-failure
    networks:
      - alonetwork
    depends_on:
      - config-server
      - eureka-server

  microservice-user:
    container_name: microservice-user
    image: microservice-user
    build:
      context: ./microservice-user
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    environment:
      CONFIG_URI: http://config-server:8888
      EUREKA_URI: http://eureka-server:8081/eureka/
    restart: on-failure
    networks:
      - alonetwork
    depends_on:
      - config-server
      - eureka-server

  microservice-ordenes:
    container_name: microservice-ordenes
    image: microservice-ordenes
    build:
      context: ./microservice-ordenes
      dockerfile: Dockerfile
    ports:
      - 8091:8091
    environment:
      CONFIG_URI: http://config-server:8888
      EUREKA_URI: http://eureka-server:8081/eureka/
    restart: on-failure
    networks:
      - alonetwork
    depends_on:
      - config-server
      - eureka-server

  eureka-server:
    container_name: eurekaServer
    image: eureka-server
    build:
      context: ./eurekaServer
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      CONFIG_URI: http://config-server:8888
    restart: on-failure
    networks:
      - alonetwork
    depends_on:
      - config-server

  config-server:
    container_name: config-server
    image: config-server
    build:
      context: ./configServer
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    restart: on-failure
    networks:
      - alonetwork

networks:
  alonetwork:
    driver: bridge
    name: alonetwork