server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuarios
          uri: http://localhost:8090
          predicates:
            - Path=/api/usuario/**
        - id: productos
          uri: http://localhost:8092
          predicates:
            - Path=/api/producto/**
        - id: ordenes
          uri: http://localhost:8091
          predicates:
            - Path=/api/orden/**