server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka/}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuarios
          uri: ${MICROSERVICE_USER_URI:http://localhost:8090}
          predicates:
            - Path=/api/usuario/**
        - id: productos
          uri: ${MICROSERVICE_PRODUCTO_URI:http://localhost:8092}
          predicates:
            - Path=/api/producto/**
        - id: ordenes
          uri: ${MICROSERVICE_ORDENES_URI:http://localhost:8091}
          predicates:
            - Path=/api/orden/**